// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHwR0sOgwgY0xrINoriI_HdL6EZr31JFU',
    appId: '1:238258672831:web:f80c1ea84d24c00ccc620a',
    messagingSenderId: '238258672831',
    projectId: 'crudapp-3e10e',
    authDomain: 'crudapp-3e10e.firebaseapp.com',
    storageBucket: 'crudapp-3e10e.appspot.com',
    measurementId: 'G-MRKKB0X0WG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXwpv8lBtKmYG_cY48EA_oimhpGCCx2ck',
    appId: '1:238258672831:android:30302e035c453953cc620a',
    messagingSenderId: '238258672831',
    projectId: 'crudapp-3e10e',
    storageBucket: 'crudapp-3e10e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjA1RCgnumNzKf8XnecTVc04xCNjFiUXk',
    appId: '1:238258672831:ios:6587e2f062977e41cc620a',
    messagingSenderId: '238258672831',
    projectId: 'crudapp-3e10e',
    storageBucket: 'crudapp-3e10e.appspot.com',
    iosBundleId: 'com.example.menu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjA1RCgnumNzKf8XnecTVc04xCNjFiUXk',
    appId: '1:238258672831:ios:9f2e22883d746ac1cc620a',
    messagingSenderId: '238258672831',
    projectId: 'crudapp-3e10e',
    storageBucket: 'crudapp-3e10e.appspot.com',
    iosBundleId: 'com.example.menu.RunnerTests',
  );
}
